### ISSUE TITLE
iOS reassigning the value doesn't work.

### ISSUE THREAD

**Issue by evgenitsn** [react-native-community/react-native-text-input-mask#47]
So I have the following issue.
I initialize the component with some predefined value 

```
<TextInputMask           
    mask={ mask }
    value={ this.props.value }
    onChangeText={ (formatted, extracted) => {
        //logic
    }}
/>
```
In the parent component I have this piece of state: 
```
currentState = {value: 'somevalue'}
originalState = {value: 'originalvalue'}
```
I have a Cancel button in my app which when I press I pass down the originalState to this component and it should update the this.props.value with 'originalValue'. The prop is passed down, I logged it in the render method to check and the new 'originalValue' is there but the value of the Component does not change. 

This happen only on iOS, on Android it works fine.

RN: 0.54
react-native-text-input-mask: latest

**Comment by kishoremw** [comment]
it is not an issue with this component. This is a react-native bug

https://github.com/facebook/react-native/issues/18272

**Comment by olegwn** [comment]
This bug has been fixed in react-native BUT when I use TextInputMask re-assigning value using setState does not work so seems like there's a bug in your library. Below are the details:

`    "react-native": "^0.57.3",
`

### This does not work with TextInputMask but will work with native TextInput

```      
  onChangeText = (text, extracted) => {
    if (text === '+7 (8' || extracted === '8') {
      this.setState({ text: '+7' });
    } else {
      this.setState({ text });
    }
  }

    <TextInputMask
        onChangeText={this.onChangeText}
        value={this.state.text}
      />
```

**Comment by kayzenkayzen** [comment]
Yes, I have the same problem. Cannot reassign the value of and input!

**Comment by igortupini** [comment]
Same on 0.59.9

**Comment by ivanzotov** [comment]
fixed in 1.0.6

**Comment by igortupini** [comment]
Replied on issue #68
Updated to 1.0.6 and the issue still happens.
Also the `clear()` ref method doesn't work on iOS as well.

**Comment by ivanzotov** [comment]
Are you using `refInput` prop to get ref?

**Comment by igortupini** [comment]
> Are you using `refInput` prop to get ref?

I'm using the `ref` prop. I actually can use the `focus()` method only the `clear()` doesn't work.
![image](https://user-images.githubusercontent.com/1246084/62394730-73fee900-b544-11e9-8d50-2576f06d9774.png)

**Comment by ivanzotov** [comment]
Changing `ref` to `refInput` should fix that

**Comment by igortupini** [comment]
@ivanzotov Changing to refInput doesn't seem to work. :(
This results on null ref. 
![image](https://user-images.githubusercontent.com/1246084/62485533-54a9cb00-b793-11e9-9f15-a9d0990bbc77.png)
![image](https://user-images.githubusercontent.com/1246084/62485546-5a071580-b793-11e9-9d59-0875c94667d5.png)
