### ISSUE TITLE
Any way to 'clear' input field? 

### ISSUE THREAD

**Issue by mkds622** [react-native-community/react-native-text-input-mask#68]
I have been trying to clear the text entered in the input field using various methods but none of them seem to be working. 

Diving into the code I found that the code manipulates the value of text in native props every time the value changes. I also found out that a callback is passed to the native 'mask' function before manipulating the native text prop. But I couldn't further debug and find out the reason why the text is not cleared.

please provide a fix or a workaround for this issue. Thanks.

**Comment by derenebdon** [comment]
https://github.com/derenebdon/react-native-text-input-mask#fixClear exposes a clear method that you can call via a ref.

**Comment by mkds622** [comment]
Does this fix work for RN 0.49.0?

**Comment by derenebdon** [comment]
No, RCTTextField was renamed to RCTSinglelineTextInputView, so that is why you can't import. I am currently on RN 0.55.

**Comment by mkds622** [comment]
So is it possible for you to provide a fix for RN 0.49? Please provide if possible.

I'm currently on RN 0.49 and my in my case updating RN above 0.50 could initiate problems in compatibility with other libraries.

**Comment by mkds622** [comment]
@derenebdon ??

**Comment by derenebdon** [comment]
Sorry, not a maintainer of this project, and no time for side projects :)   We have already done a RN 0.49 -> RN 0.55 and a RN 0.55 -> RN 0.57 transition for our projects.  It was definitely work, but maybe better than you might think.

**Comment by johhansantana** [comment]
any update on this?

**Comment by igortupini** [comment]
Anu update on this?

**Comment by ivanzotov** [comment]
Fixed in 1.0.6, please try the new version

**Comment by igortupini** [comment]
> Fixed in 1.0.6, please try the new version

@ivanzotov Tried new version (1.0.6) and the issue still happens. And still only on iOS.
Also the `clear()` ref method doesn't work only on iOS as well.
